// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeTnHLQ9Ds5oHtv-eIV8e2dG4uCUafCl8',
    appId: '1:431193258328:web:46123958f347ac6b300d2d',
    messagingSenderId: '431193258328',
    projectId: 'breathe-app-95c7a',
    authDomain: 'breathe-app-95c7a.firebaseapp.com',
    storageBucket: 'breathe-app-95c7a.firebasestorage.app',
    measurementId: 'G-W8R08KNB1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaiMG1YHdKAadoZWZmDVZnSRjK117Mi3Y',
    appId: '1:431193258328:android:c4aa5023184e3e29300d2d',
    messagingSenderId: '431193258328',
    projectId: 'breathe-app-95c7a',
    storageBucket: 'breathe-app-95c7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPGbWP7A5FVLsqR7IxzSDKm_6HvYFrezo',
    appId: '1:431193258328:ios:0d5199d29ddc1cb2300d2d',
    messagingSenderId: '431193258328',
    projectId: 'breathe-app-95c7a',
    storageBucket: 'breathe-app-95c7a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPGbWP7A5FVLsqR7IxzSDKm_6HvYFrezo',
    appId: '1:431193258328:ios:0d5199d29ddc1cb2300d2d',
    messagingSenderId: '431193258328',
    projectId: 'breathe-app-95c7a',
    storageBucket: 'breathe-app-95c7a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeTnHLQ9Ds5oHtv-eIV8e2dG4uCUafCl8',
    appId: '1:431193258328:web:6bcfdd37b7d089cf300d2d',
    messagingSenderId: '431193258328',
    projectId: 'breathe-app-95c7a',
    authDomain: 'breathe-app-95c7a.firebaseapp.com',
    storageBucket: 'breathe-app-95c7a.firebasestorage.app',
    measurementId: 'G-KF01HVSMVX',
  );
}
